-- MySQL Script generated by MySQL Workbench
-- Mon May 16 21:39:13 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Leandro_Moschner_LawOffice
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Leandro_Moschner_LawOffice
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Leandro_Moschner_LawOffice` DEFAULT CHARACTER SET utf8 ;
USE `Leandro_Moschner_LawOffice` ;

-- -----------------------------------------------------
-- Table `Leandro_Moschner_LawOffice`.`Country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Leandro_Moschner_LawOffice`.`Country` (
  `id_Country` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id_Country`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Leandro_Moschner_LawOffice`.`Cities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Leandro_Moschner_LawOffice`.`Cities` (
  `id_Cities` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `Country_id_Country` INT NOT NULL,
  PRIMARY KEY (`id_Cities`),
  INDEX `fk_Cities_Country1_idx` (`Country_id_Country` ASC) VISIBLE,
  CONSTRAINT `fk_Cities_Country1`
    FOREIGN KEY (`Country_id_Country`)
    REFERENCES `Leandro_Moschner_LawOffice`.`Country` (`id_Country`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Leandro_Moschner_LawOffice`.`Address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Leandro_Moschner_LawOffice`.`Address` (
  `id_Address` INT NOT NULL AUTO_INCREMENT,
  `postal_code` INT NULL,
  `street_name` VARCHAR(45) NULL,
  `street_number` INT NULL,
  `Cities_id_Cities` INT NOT NULL,
  PRIMARY KEY (`id_Address`),
  INDEX `fk_Address_Cities1_idx` (`Cities_id_Cities` ASC) VISIBLE,
  CONSTRAINT `fk_Address_Cities1`
    FOREIGN KEY (`Cities_id_Cities`)
    REFERENCES `Leandro_Moschner_LawOffice`.`Cities` (`id_Cities`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Leandro_Moschner_LawOffice`.`Clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Leandro_Moschner_LawOffice`.`Clients` (
  `id_clients` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `Address_id_Address` INT NOT NULL,
  PRIMARY KEY (`id_clients`),
  INDEX `fk_Clients_Address1_idx` (`Address_id_Address` ASC) VISIBLE,
  CONSTRAINT `fk_Clients_Address1`
    FOREIGN KEY (`Address_id_Address`)
    REFERENCES `Leandro_Moschner_LawOffice`.`Address` (`id_Address`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Leandro_Moschner_LawOffice`.`Employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Leandro_Moschner_LawOffice`.`Employees` (
  `id_Employees` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `salary` INT NULL,
  `Address_id_Address` INT NOT NULL,
  PRIMARY KEY (`id_Employees`),
  INDEX `fk_Adm_Employees_Address1_idx` (`Address_id_Address` ASC) VISIBLE,
  CONSTRAINT `fk_Adm_Employees_Address1`
    FOREIGN KEY (`Address_id_Address`)
    REFERENCES `Leandro_Moschner_LawOffice`.`Address` (`id_Address`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Leandro_Moschner_LawOffice`.`Judge`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Leandro_Moschner_LawOffice`.`Judge` (
  `id_Judge` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `Address_id_Address` INT NOT NULL,
  PRIMARY KEY (`id_Judge`),
  INDEX `fk_Judge_Address1_idx` (`Address_id_Address` ASC) VISIBLE,
  CONSTRAINT `fk_Judge_Address1`
    FOREIGN KEY (`Address_id_Address`)
    REFERENCES `Leandro_Moschner_LawOffice`.`Address` (`id_Address`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Leandro_Moschner_LawOffice`.`Courts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Leandro_Moschner_LawOffice`.`Courts` (
  `id_Courts` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `Address_id_Address` INT NOT NULL,
  PRIMARY KEY (`id_Courts`),
  INDEX `fk_Courts_Address1_idx` (`Address_id_Address` ASC) VISIBLE,
  CONSTRAINT `fk_Courts_Address1`
    FOREIGN KEY (`Address_id_Address`)
    REFERENCES `Leandro_Moschner_LawOffice`.`Address` (`id_Address`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Leandro_Moschner_LawOffice`.`Cases`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Leandro_Moschner_LawOffice`.`Cases` (
  `id_Cases` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `defendant` VARCHAR(45) NULL,
  `Courts_id_Courts` INT NOT NULL,
  `Judge_id_Judge` INT NOT NULL,
  PRIMARY KEY (`id_Cases`),
  INDEX `fk_Cases_Courts1_idx` (`Courts_id_Courts` ASC) VISIBLE,
  INDEX `fk_Cases_Judge1_idx` (`Judge_id_Judge` ASC) VISIBLE,
  CONSTRAINT `fk_Cases_Courts1`
    FOREIGN KEY (`Courts_id_Courts`)
    REFERENCES `Leandro_Moschner_LawOffice`.`Courts` (`id_Courts`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cases_Judge1`
    FOREIGN KEY (`Judge_id_Judge`)
    REFERENCES `Leandro_Moschner_LawOffice`.`Judge` (`id_Judge`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Leandro_Moschner_LawOffice`.`Jury_Members`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Leandro_Moschner_LawOffice`.`Jury_Members` (
  `idJury_Members` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `Address_id_Address` INT NOT NULL,
  `Cases_id_Cases` INT NOT NULL,
  PRIMARY KEY (`idJury_Members`),
  INDEX `fk_Jury_Members_Address1_idx` (`Address_id_Address` ASC) VISIBLE,
  INDEX `fk_Jury_Members_Cases1_idx` (`Cases_id_Cases` ASC) VISIBLE,
  CONSTRAINT `fk_Jury_Members_Address1`
    FOREIGN KEY (`Address_id_Address`)
    REFERENCES `Leandro_Moschner_LawOffice`.`Address` (`id_Address`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Jury_Members_Cases1`
    FOREIGN KEY (`Cases_id_Cases`)
    REFERENCES `Leandro_Moschner_LawOffice`.`Cases` (`id_Cases`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Leandro_Moschner_LawOffice`.`Receipts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Leandro_Moschner_LawOffice`.`Receipts` (
  `id_Receipts` INT NOT NULL AUTO_INCREMENT,
  `from` VARCHAR(45) NULL,
  `to` VARCHAR(45) NULL,
  `amount` VARCHAR(45) NULL,
  `date` VARCHAR(45) NULL,
  PRIMARY KEY (`id_Receipts`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Leandro_Moschner_LawOffice`.`Payments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Leandro_Moschner_LawOffice`.`Payments` (
  `id_Payments` INT NOT NULL AUTO_INCREMENT,
  `amount` INT NULL,
  `date` DATE NULL,
  `Receipts_id_Receipts` INT NOT NULL,
  `Clients_id_clients` INT NULL,
  `id_Employees` INT NULL,
  PRIMARY KEY (`id_Payments`, `Receipts_id_Receipts`),
  INDEX `fk_Payments_Receipts1_idx` (`Receipts_id_Receipts` ASC) VISIBLE,
  INDEX `fk_Payments_Clients1_idx` (`Clients_id_clients` ASC) VISIBLE,
  INDEX `fk_Payments_Adm_Employees1_idx` (`id_Employees` ASC) VISIBLE,
  CONSTRAINT `fk_Payments_Receipts1`
    FOREIGN KEY (`Receipts_id_Receipts`)
    REFERENCES `Leandro_Moschner_LawOffice`.`Receipts` (`id_Receipts`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Payments_Clients1`
    FOREIGN KEY (`Clients_id_clients`)
    REFERENCES `Leandro_Moschner_LawOffice`.`Clients` (`id_clients`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Payments_Adm_Employees1`
    FOREIGN KEY (`id_Employees`)
    REFERENCES `Leandro_Moschner_LawOffice`.`Employees` (`id_Employees`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Leandro_Moschner_LawOffice`.`Lawyer_Licenses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Leandro_Moschner_LawOffice`.`Lawyer_Licenses` (
  `id_LawyerLicences` INT NOT NULL AUTO_INCREMENT,
  `expiration_date` DATE NULL,
  `id_Employees` INT NOT NULL,
  PRIMARY KEY (`id_LawyerLicences`, `id_Employees`),
  INDEX `fk_Lawyer_Licenses_Employees1_idx` (`id_Employees` ASC) VISIBLE,
  CONSTRAINT `fk_Lawyer_Licenses_Employees1`
    FOREIGN KEY (`id_Employees`)
    REFERENCES `Leandro_Moschner_LawOffice`.`Employees` (`id_Employees`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Leandro_Moschner_LawOffice`.`Case_Docs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Leandro_Moschner_LawOffice`.`Case_Docs` (
  `id_CaseDocs` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `Cases_id_Cases` INT NOT NULL,
  PRIMARY KEY (`id_CaseDocs`, `Cases_id_Cases`),
  INDEX `fk_Case_Docs_Cases1_idx` (`Cases_id_Cases` ASC) VISIBLE,
  CONSTRAINT `fk_Case_Docs_Cases1`
    FOREIGN KEY (`Cases_id_Cases`)
    REFERENCES `Leandro_Moschner_LawOffice`.`Cases` (`id_Cases`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Leandro_Moschner_LawOffice`.`Plaintiffies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Leandro_Moschner_LawOffice`.`Plaintiffies` (
  `id_Demandent` INT NOT NULL AUTO_INCREMENT,
  `Clients_id_clients` INT NOT NULL,
  `Cases_id_Cases` INT NOT NULL,
  PRIMARY KEY (`id_Demandent`, `Cases_id_Cases`),
  INDEX `fk_Plaintiffies_Clients1_idx` (`Clients_id_clients` ASC) VISIBLE,
  INDEX `fk_Plaintiffies_Cases1_idx` (`Cases_id_Cases` ASC) VISIBLE,
  CONSTRAINT `fk_Plaintiffies_Clients1`
    FOREIGN KEY (`Clients_id_clients`)
    REFERENCES `Leandro_Moschner_LawOffice`.`Clients` (`id_clients`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Plaintiffies_Cases1`
    FOREIGN KEY (`Cases_id_Cases`)
    REFERENCES `Leandro_Moschner_LawOffice`.`Cases` (`id_Cases`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Leandro_Moschner_LawOffice`.`Court_Schedules`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Leandro_Moschner_LawOffice`.`Court_Schedules` (
  `id_Schedules` INT NOT NULL AUTO_INCREMENT,
  `id_Courts` INT NOT NULL,
  `id_Judge` INT NOT NULL,
  `dateAndTime` DATE NULL,
  PRIMARY KEY (`id_Schedules`, `id_Courts`),
  INDEX `fk_Court_Schedules_Courts1_idx` (`id_Courts` ASC) VISIBLE,
  INDEX `fk_Court_Schedules_Judge1_idx` (`id_Judge` ASC) VISIBLE,
  CONSTRAINT `fk_Court_Schedules_Courts1`
    FOREIGN KEY (`id_Courts`)
    REFERENCES `Leandro_Moschner_LawOffice`.`Courts` (`id_Courts`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Court_Schedules_Judge1`
    FOREIGN KEY (`id_Judge`)
    REFERENCES `Leandro_Moschner_LawOffice`.`Judge` (`id_Judge`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Leandro_Moschner_LawOffice`.`Case_Orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Leandro_Moschner_LawOffice`.`Case_Orders` (
  `id_CaseOrders` INT NOT NULL AUTO_INCREMENT,
  `Cases_id_Cases` INT NOT NULL,
  `Employees_id_Employees` INT NOT NULL,
  PRIMARY KEY (`id_CaseOrders`, `Cases_id_Cases`),
  INDEX `fk_Case_Orders_Cases1_idx` (`Cases_id_Cases` ASC) VISIBLE,
  INDEX `fk_Case_Orders_Employees1_idx` (`Employees_id_Employees` ASC) VISIBLE,
  CONSTRAINT `fk_Case_Orders_Cases1`
    FOREIGN KEY (`Cases_id_Cases`)
    REFERENCES `Leandro_Moschner_LawOffice`.`Cases` (`id_Cases`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Case_Orders_Employees1`
    FOREIGN KEY (`Employees_id_Employees`)
    REFERENCES `Leandro_Moschner_LawOffice`.`Employees` (`id_Employees`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
